eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost 
    
microservice:
  movie-info-service: 
    endpoints:
      endpoint:
        uri: http://movie-info-service/movies/{movieId}
  rating-data-service:
    endpoints:
      endpoint:
        uri: http://rating-data-service/ratingsdata/user/{userId}
